name: Build and deploy

on:
  push:
    branches:
      - master
        
env:
  PROJECT_NAME: frostorchunter
        
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-24.04
    strategy:
      matrix: 
        targetPlatform:
          - WebGL
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      
      - uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-${{ env.PROJECT_NAME }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ env.PROJECT_NAME }}-${{ matrix.unityVersion }}-
            Library-${{ env.PROJECT_NAME }}-
            Library-
            
      - name: debug prints
        run: |
          echo "${{ secrets.UNITY_LICENSE }}"
          echo "${{ secrets.UNITY_EMAIL }}"
          echo "${{ secrets.UNITY_PASSWORD }}"
            
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./
          unityVersion: 6000.0.41f1
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ env.PROJECT_NAME }}
          buildsPath: build/${{ matrix.targetPlatform }}
          
      - uses: manleydev/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: ${{ env.PROJECT_NAME }}
          ITCH_USER: zeph1rr
          PACKAGE: build/${{ matrix.targetPlatform }}