name: Build and deploy

on:
  push:
    branches:
      - master
        
env:
  PROJECT_NAME: frostorchunter
        
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-24.04
    strategy:
      matrix: 
        targetPlatform:
          - WebGL
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
          
      - name: Configure Git credentials
        env:
          USERNAME: ${{ secrets.GH_USERNAME }}
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global credential.helper store

          echo "https://${USERNAME}:${TOKEN}@github.com" >> ~/.git-credentials

          if [ -f ~/.git-credentials ]; then
            echo "Git credentials configured successfully"
            # Безопасная проверка (не выводим содержимое)
            ls -la ~/.git-credentials
          else
            echo "Error: Failed to create git-credentials file"
            exit 1
          fi
          
      - name: Test Git access
        run: |
          git ls-remote https://github.com/zeph1rr/zeph1rrgamebase.git HEAD
            
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ env.PROJECT_NAME }}
          
      - uses: manleydev/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: ${{ env.PROJECT_NAME }}
          ITCH_USER: zeph1rr
          PACKAGE: build/${{ matrix.targetPlatform }}